#!/bin/bash

# This script checks the wp-config.php file for important values.
# Useful to check for differences from standard install values, or check for problematic settings.
# Also useful to scan wp-config.migration.php for old settings during migrations.
#
# Usage: $ check-wp-config <path to wp-config.php>
#
# Scans available:
# * WP $table_prefix value
#
# @TODO - Check for WP_DEBUG true/false
# @TODO - Cookie & session constants.

CONFIGPATH="${1:-wp-config.php}"

SUCCESS=✅
ERROR=❌
NOTE=ℹ️

if ! test -f $CONFIGPATH
then
    echo "$ERROR Cannot locate file $CONFIGPATH"
    exit
fi

TABLE_PREFIX=`grep '^\$table_prefix' $CONFIGPATH | cut -d \' -f 2`

if [ $TABLE_PREFIX == 'wp_' ]
then
    echo "$SUCCESS Standard table prefix found: $TABLE_PREFIX"
else
    echo "$NOTE Custom table prefix found: $TABLE_PREFIX"
fi