#!/bin/bash

# This script scans the wp-contents directory for problematic plugins and themes.
# See the following URL: https://docs.pantheon.io/plugins-known-issues

# Last updated: Mar 5, 2024

WP_CONTENT_PATH="${1:-.}"

PROBLEM_PLUGINS=(
    "accelerated-mobile-pages"
    "adthrive-ads"
    "all-in-one-wp-migration"
    "all-in-one-wp-migration-multisite-extension"
    "autoptimize"
    "batcache"
    "better-search-replace"
    "better-search-replace-pro"
    "better-wp-security"
    "bookly"
    "broken-link-checker"
    "coming-soon"
    "constant-contact-forms"
    "contact-form-7"
    "cookie-law-info"
    "disable-rest-api-and-require-jwt-oauth-authentication"
    "divi"
    "easy-theme-and-plugin-upgrades"
    "elementor"
    "event-espresso"                    # verify slug @TODO
    "fast-velocity-minify"
    "facet-wp"                          # verify slug @TODO
    "git-updater"
    "git-updater-bitbucket"
    "git-updater-pro"
    "h5p"
    "hm-require-login"
    "hummingbird-performance"
    "hyperdb"
    "infinitewp"                        # verify slug @TODO
    "instagram-feed-instashow"          # verify slug @TODO
    "instagram-instashow"               # verify slug @TODO
    "jetpack"
    "live-weather-station"
    "lj-maintenance-mode"
    "monarch"
    "nextgen-gallery"
    "next-active-directory-integration"
    "object-sync-for-salesforce"
    "official-facebook-pixel"
    "one-click-demo-import"
    "popup-builder"
    "polylang"
    "posts-to-posts"
    "query-monitor"
    "nitropack"
    "redirection"
    "sendgrid-email-delivery-simplified"
    "site24x7-rum"
    "slider-revolution"                 # verify slug @TODO
    "smartcrawl-wordpress-seo"          # verify slug @TODO
    "smush"                             # verify slug @TODO
    "timthumb"
    "tweet-old-post"
    "tubepress"                         # verify slug @TODO
    "unbounce"
    "unloq"
    "unyson"
    "updraftplus"
    "visual-composer"                   # verify slug @TODO
    "visualcomposer"                    # verify slug @TODO
    "w3-total-cache"
    "webp-express"
    "woocommerce"
    "woocommerce-amazon-affiliates"     # verify slug @TODO
    "wordpress-download-manager"        # verify slug @TODO
    "wordpress-seo"
    "wordpress-seo-indexables"          # verify slug @TODO
    "indexables"                        # verify slug @TODO (duplicate of above)
    "wordpress-social-login"
    "wordfence"
    "worker"
    "wp-bakery"                         # verify slug @TODO
    "wpbakery"                          # verify slug @TODO (duplicate of above)
    "wp-ban"
    "wp-cerber"
    "wp-fastest-cache"
    "wp-force-login"
    "wp-migrate-db"
    "wp-newrelic"
    "wp-phpmyadmin"                     # verify slug @TODO
    "wp-smush-pro"
    "wp-supercache"
    "wp-reset"
    "wp-rocket"
    "wpmudev-updates"
    "wpallimport"
    "wpallexport"
    "wpdownloadmanager"
    "wpfront-notification-bar"
    "wpml"                              # verify slug @TODO
    "yith-woocommerce-request-a-quote"  # verify slug @TODO
    "yith-woocommerce-pdf-invoice"      # verify slug @TODO
    "yith-woocommerce-gift-cards"       # verify slug @TODO
    "yotuwp-easy-youtube-embed"
)

PROBLEM_THEMES=(
    "divi"
    "jupiter"
    "nanosoft"
    "uncode"
)

SUCCESS=✅
ERROR=❌
NOTE=ℹ️

# PLUGINS
INSTALLED_PLUGINS=()
FOUND_PLUGINS=()
PLUGINS_PATH=$WP_CONTENT_PATH/plugins

if ! test -d $WP_CONTENT_PATH
then
    echo "$ERROR Cannot locate wp-content path $WP_CONTENT_PATH"
    exit
fi

echo "Scanning $PLUGINS_PATH ..."

# scan for list of all plugins
for dir in $PLUGINS_PATH/*/                         # list directories in the form "/tmp/dirname/"
do
    dir=${dir%*/}                                   # remove the trailing "/"
    dir=${dir##*/}                                  # everything after last slash
    dir=`echo $dir | tr '[:upper:]' '[:lower:]'`    # convert to lowercase
    INSTALLED_PLUGINS+=( "${dir}" )
done

# compare installed plugins against list of known assumed write plugins a
# save any matches to the FOUND_PLUGINS array
for installed in "${INSTALLED_PLUGINS[@]}"; do
    for check in "${PROBLEM_PLUGINS[@]}"; do
        if [[ $installed = $check ]]; then
            FOUND_PLUGINS+=( "$installed" )
        fi
    done
done

# Return scan results
if [ ${#FOUND_PLUGINS[@]} -gt 0 ]
then
    echo "$ERROR  Found the following problematic PLUGINS:"
    for plugin in "${FOUND_PLUGINS[@]}"
    do
        echo "- $plugin"
    done
    echo "Apply fixes from URL: https://docs.pantheon.io/plugins-known-issues"
else
    echo "$SUCCESS  No problematic PLUGINS found."
fi

echo "-----"

# THEMES
INSTALLED_THEMES=()
FOUND_THEMES=()
THEMES_PATH=$WP_CONTENT_PATH/themes

echo "Scanning $THEMES_PATH ..."

# scan for list of all themes
for dir in $THEMES_PATH/*/                          # list directories in the form "/tmp/dirname/"
do
    dir=${dir%*/}                                   # remove the trailing "/"
    dir=${dir##*/}                                  # everything after last slash
    dir=`echo $dir | tr '[:upper:]' '[:lower:]'`    # convert to lowercase
    INSTALLED_THEMES+=( "${dir}" )
done

# compare installed themes against list of known problematic themes
# save any matches to the FOUND_THEMES array
for installed in "${INSTALLED_THEMES[@]}"; do
    for check in "${PROBLEM_THEMES[@]}"; do
        if [[ $installed = $check ]]; then
            FOUND_THEMES+=( "$installed" )
        fi
    done
done

# Return scan results
if [ ${#FOUND_THEMES[@]} -gt 0 ]
then
    echo "$ERROR  Found the following problmatic THEMES:"
    for theme in "${FOUND_THEMES[@]}"
    do
        echo "- $theme"
    done
    echo "Apply fixes from URL: https://docs.pantheon.io/plugins-known-issues"
else
    echo "$SUCCESS  No problematic THEMES found."
fi